- lib/global/cache/index.dart
- lib/global/cache/serializer.dart
- lib/store/index.dart
- lib/store/rooms/actions.dart
- lib/store/settings/actions.dart
- lib/store/sync/actions.dart
- lib/store/sync/background/service.dart
- lib/views/home/index.dart
- pubspec.lock
- pubspec.yaml
Better notification content in addition
> [0.1.4] Securing Background Sync Thread

- lib/global/cache/index.dart
- lib/global/colours.dart
- lib/store/auth/actions.dart
- lib/store/crypto/events/actions.dart
- lib/store/rooms/actions.dart
- pubspec.yaml
- version.txt
Several small tweaks for performance and a couple bugs when signing out/in
also version bumps for fdroid
> [bugfix] small tweaks

- lib/cache/serializer.dart
- lib/global/algos.dart
- lib/global/strings.dart
- lib/global/values.dart
- lib/main.dart
- lib/storage/index.dart
- lib/store/events/actions.dart
- lib/store/events/messages/model.dart
- lib/store/events/model.dart
- lib/store/events/parsers.dart
- lib/store/events/reactions/model.dart
- lib/store/events/redaction/model.dart
- lib/store/events/redaction/selectors.dart
- lib/store/events/reducer.dart
- lib/store/events/selectors.dart
- lib/store/events/state.dart
- lib/store/events/storage.dart
- lib/store/rooms/actions.dart
- lib/store/rooms/room/model.dart
- lib/views/home/chat/index.dart
- lib/views/widgets/messages/message.dart
Needed to toggle reactions and 'delete' messages server side
> [feat] Redactions (Messages & Reactions)

- assets/cheatsheet.md
- lib/cache/serializer.dart
- lib/main.dart
- lib/storage/constants.dart
- lib/storage/index.dart
- lib/storage/middleware.dart
- lib/store/auth/actions.dart
- lib/store/events/actions.dart
- lib/store/events/ephemeral/m.read/model.dart
- lib/store/events/receipts/storage.dart
- lib/store/events/reducer.dart
- lib/store/events/state.dart
- lib/store/events/storage.dart
- lib/store/rooms/actions.dart
- lib/store/rooms/reducer.dart
- lib/store/rooms/room/model.dart
- lib/store/rooms/storage.dart
- lib/store/settings/notification-settings/actions.dart
- lib/views/home/chat/details-message.dart
- lib/views/signup/index.dart
- lib/views/signup/step-homeserver.dart
- lib/views/signup/verification.dart
- lib/views/widgets/lists/list-user-bubbles.dart
Issues surrounding saving receipts to cold storage are mostly fixed. 
Still not saving entirely correctly, but performance is drastically better now that they are not continually added to the room model.
> [fix] Read Receipts

- lib/storage/constants.dart
- lib/storage/index.dart
- lib/store/auth/storage.dart
- lib/store/crypto/storage.dart
- lib/store/events/parsers.dart
- lib/store/events/receipts/storage.dart
- lib/store/events/storage.dart
- lib/store/media/storage.dart
- lib/store/rooms/actions.dart
- lib/store/rooms/room/model.dart
- lib/store/sync/actions.dart
- lib/store/user/storage.dart
- lib/views/home/chat/index.dart
- lib/views/widgets/messages/message-typing.dart
- pubspec.yaml
offloading room and message parsing from main thread, better cold storage handling for receipts
Still needs better initial sync performance
> [hotfix] Performance Syncing & Receipt Storage

- .drone.yml
Just adding my CI config from https://git.0x1a8510f2.space/0x1a8510f2/external-build-configs/src/branch/master/syphon.yml / https://ci.0x1a8510f2.space/0x1a8510f2/syphon as a starting point for the new CI configs :D
> [chore] Deployment Pipeline Starter

- .drone.yml
- lib/views/intro/search/search-homeserver-screen.dart
Setup pipeline for linux deployments
> [chore] linux dev/prod release pipeline

- .drone.yml
> fix: small tweaks to drone deployment

- android/gradle/wrapper/gradle-wrapper.properties
Quick and tiny fix for #293 because I was bored. Saves you opening the file I guess xP
Fixes #293 ( because GitHub won't realise unless I use the exact right words :/ )
> Remove trailing space in gradle-wrapper.properties (fix #293)

- lib/store/settings/theme-settings/selectors.dart
- lib/views/home/chat/widgets/chat-input.dart
- Fix #290
- Use selectors to determine the color of the chat input box (easier to change hardcoded values as they are in one file)
https://user-images.githubusercontent.com/83190128/125163077-43d61100-e183-11eb-83d4-ea85c442f78f.mp4
> Chat input tweaks (better dark mode theme and switch to selectors)

- lib/cache/serializer.dart
- lib/global/strings.dart
- lib/storage/constants.dart
- lib/storage/index.dart
- lib/storage/middleware.dart
- lib/store/auth/middleware.dart
- lib/store/auth/state.dart
- lib/store/crypto/actions.dart
- lib/store/crypto/events/actions.dart
- lib/store/crypto/events/selectors.dart
- lib/store/crypto/keys/actions.dart
- lib/store/crypto/reducer.dart
- lib/store/crypto/state.dart
- lib/store/crypto/storage.dart
- lib/store/events/actions.dart
- lib/store/events/messages/actions.dart
- lib/store/events/messages/model.dart
- lib/store/events/model.dart
- lib/store/events/receipts/storage.dart
- lib/store/events/reducer.dart
- lib/store/events/selectors.dart
- lib/store/events/state.dart
- lib/store/events/storage.dart
- lib/store/rooms/actions.dart
- lib/store/rooms/room/model.dart
- lib/store/sync/actions.dart
- lib/views/home/chat/chat-screen.dart
- lib/views/home/home-screen.dart
- lib/views/intro/intro-screen.dart
> [fix] Decryption Issues

- .gitignore
- fastlane/metadata/android/en-US/changelogs/215.txt
- lib/store/auth/reducer.dart
- pubspec.yaml
- version.txt
- Issue with inability to complete email verification (any multi step onboarding)
> [hotfix] Onboarding Regression

- .drone.yml
- .github/pull_request_template.md
- android/app/src/main/AndroidManifest.xml
- contributing.md
- docs/code-of-conduct.md
- readme.md
> [chore] Docs

- lib/cache/index.dart
- lib/context/index.dart
- lib/context/types.dart
- lib/main.dart
- lib/storage/index.dart
- lib/storage/moor/database.dart
- lib/views/syphon.dart
- pubspec.lock
> fix: issue saving new cold cache on android

- android/app/src/main/AndroidManifest.xml
- lib/views/home/chat/media-preview-screen.dart
- lib/views/home/chat/widgets/chat-input.dart
- lib/views/widgets/lists/list-local-images.dart
- pubspec.lock
- pubspec.yaml
> [fix] media message issue android

- lib/global/libs/matrix/events.dart
- lib/global/libs/matrix/index.dart
- lib/global/libs/matrix/rooms.dart
- lib/storage/middleware.dart
- lib/store/events/actions.dart
- lib/store/events/messages/model.dart
- lib/store/events/reducer.dart
- lib/store/events/selectors.dart
- lib/views/home/chat/chat-screen.dart
- lib/views/widgets/appbars/appbar-options-message.dart
First draft for deleting messages
- Deleting Messages (Sent / Remotely)
> [feature] first draft for delete messages

- lib/storage/drift/database.dart
- lib/storage/drift/migrations/update.messages.5.dart
- lib/storage/index.dart
- lib/store/rooms/reducer.dart
- lib/store/rooms/room/model.dart
- lib/store/sync/background/service.dart
- lib/views/home/chat/chat-screen.dart
- lib/views/home/chat/media-preview-screen.dart
- lib/views/home/chat/widgets/chat-input.dart
- lib/views/home/chat/widgets/message-list.dart
- lib/views/home/settings/advanced-settings-screen.dart
- pubspec.yaml
> [hotfix] various issues 0.2.2

- windows/runner/Runner.rc
> chore: fix Windows executable description strings

- lib/store/alerts/model.dart
> chore: Extend error duration to 8 seconds from 3

- lib/global/https.dart
- lib/global/libs/matrix/devices.dart
- lib/global/libs/matrix/events.dart
- lib/global/libs/matrix/media.dart
- lib/global/libs/matrix/rooms.dart
- lib/global/libs/matrix/user.dart
- lib/main.dart
- lib/store/media/actions.dart
- lib/store/settings/reducer.dart
- lib/store/sync/actions.dart
No need for a separate "ProxiedClient" method now
> [fix] proxy fixes

- .github/pull_request_template.md
- changelog.md
- fastlane/metadata/android/en-US/changelogs/2005.txt
- lib/global/platform.dart
- lib/views/widgets/input/text-field-secure.dart
- readme.md
- version.txt
> chore: documentation updates

- .drone.yml
Duplicated the current Linux main&dev pipeline and specified one to run on ARM64 hardware and the other to run on AMD64 hardware for ARM64 and AMD64 builds. I also specified the AMD64 hardware for builds from other branches to make sure they run on AMD64 hardware. Otherwise some builds would run on ARM64 and some on AMD64 producing their respective binaries near-randomly, as long as both types of hardware are connected to Drone. Didn't touch Android builds as it, as far as I know, doesn't matter where they are built, although since the AMD64 build hardware is currently better than the ARM64 ones, it might be worth specifying AMD64 for regularly faster builds.
> Add ARM64 Linux pipeline to .drone.yml + update push container

- .drone.yml
> [chore] drone updates

- ios/Podfile.lock
- lib/views/home/chat/chat-detail-screen.dart
- lib/views/intro/signup/widgets/StepCaptcha.dart
- lib/views/intro/signup/widgets/StepUsername.dart
- lib/views/widgets/captcha.dart
- lib/views/widgets/dialogs/dialog-captcha.dart
- lib/views/widgets/input/text-field-secure.dart
> fix: signup flow issues

- windows/runner/Runner.rc
> chore: Windows Executable parity with other builds

- lib/storage/middleware/save-storage-middleware.dart
- lib/views/intro/login/login-screen.dart
Forgot to save proxy auth settings each time they are edited, sorry...
> [fix] Save proxy auth settings, please merge before 0.2.8

- .drone.yml
Some of the libs copied into the Linux bundle are symlinks which is no good. Added `-L` to cp to hopefully fix this. Forgot to do this in https://github.com/syphon-org/syphon/pull/491.
> [chore] Follow symlinks when copying libs for Linux

- android/gradle/wrapper/gradle-wrapper.properties
Change gradle version in gradle-wrapper to the new one
> [fix] change gradle version to the new one

- .fvm/fvm_config.json
- assets/payloads/fix-batch-names.txt
- lib/storage/middleware/save-storage-middleware.dart
- lib/store/settings/actions.dart
- lib/store/settings/storage.dart
- lib/views/intro/intro-screen.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
> [fix] Various Issues Batch - Aqua

- lib/global/platform.dart
PathProviderLinux moved the method we used to hook into Syphon (Fixes #566 ?)
> [fix] PathProviderLinux moved its register method

- lib/global/platform.dart
> Revert "[fix] PathProviderLinux moved its register method"

- android/app/src/main/AndroidManifest.xml
> [chore] migrate to Android Embedding v2

- lib/global/libs/matrix/auth.dart
- lib/global/libs/matrix/index.dart
- lib/global/values.dart
- lib/store/auth/actions.dart
- lib/store/auth/selectors.dart
- lib/store/auth/state.dart
- Allow login with 3pids (Third-Party IDs)
> [feature] Support 3pids (email/msisdn) for logins

- assets/translations/en.json
- ios/Podfile.lock
- lib/global/strings.dart
- lib/views/home/chat/widgets/chat-input.dart
> [refactor] Hide Send Button

- lib/views/widgets/image-matrix.dart
- lib/views/widgets/messages/message.dart
- pubspec.yaml
Through this pull request it is possible to display images in fullscreen mode with zoom
> [feature] fullscreen images

- lib/views/home/chat/media-full-screen.dart
- lib/views/widgets/image-matrix.dart
- lib/views/widgets/messages/message.dart
- pubspec.yaml
> [refactor] fullscreen images

- lib/views/widgets/messages/message.dart
Respect soft line breaks in markdown (Fixes #589)
> fix: Respect soft line breaks in messages

- docs/faq-en.md
> [chore] plump out the FAQ

- assets/translations/en.json
- lib/global/strings.dart
- lib/views/home/settings/settings-privacy-screen.dart
Copy session key to clipboard from Settings->Privacy (Part Fix https://github.com/syphon-org/syphon/issues/477)
> [Feature] Copy session key to clipboard from settings-> privacy screen

- assets/translations/en.json
- lib/global/strings.dart
- lib/views/home/settings/settings-privacy-screen.dart
Copy session ID to clipboard from Settings->Privacy (Part Fix #477)
> [Feature] Copy session ID to clipboard from settings-> privacy screen

- lib/views/home/settings/settings-privacy-screen.dart
> [fix] Missing closing brace

- lib/global/libs/matrix/index.dart
- lib/global/libs/matrix/media.dart
- lib/views/home/chat/media-full-screen.dart
- lib/views/widgets/messages/message.dart
- pubspec.yaml
Share and download button added ![Screenshot_20220409-090830_Syphon.png](https://user-images.githubusercontent.com/54689374/162561019-9af8b668-5581-4100-b9b1-15b595410023.png)
> [Feature] adjustments full screen images

- .github/pull_request_template.md
Update PR template to ask for linting
> [chore] update PR template to add linting

- assets/translations/en-gb.json
> [feature] add English (🇬🇧) translation

- .drone.yml
- lib/global/platform.dart
- lib/storage/database.dart
- lib/storage/index.dart
- lib/store/auth/storage.dart
- lib/store/crypto/sessions/storage.dart
- lib/store/crypto/storage.dart
- lib/store/events/messages/storage.dart
- lib/store/events/reactions/storage.dart
- lib/store/events/receipts/storage.dart
- lib/store/media/storage.dart
- lib/store/rooms/storage.dart
- lib/store/settings/storage.dart
- lib/store/sync/storage.dart
- lib/store/user/storage.dart
- linux/flutter/CMakeLists.txt
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> [fix] linux storage issues

- readme.md
- Flathub button added
- App Store link changed to the international format
> Added Flathub button to readme.md

- lib/views/home/profile/profile-user-screen.dart
Closes #697 - Error viewing detailed profile information
> [fix] Fix extended profile widget

- docs/faq-en.md
- Added missing step on Text Verification
- Added steps for importing keys from Element, adapted from the helpful steps provided by @crypt:tchncs.de
> [Chore] Update FAQ

- lib/global/values.dart
List Toki Pona as a language. I'll work on translation later...
> [i18n] Toki Pona is A Thing™

- lib/views/widgets/appbars/appbar-options-message.dart
> [fix] Share button now works

- .fvm/fvm_config.json
- .gitignore
- .gitmodules
- .vscode/settings.json
- android/app/build.gradle
- lib/cache/middleware.dart
- lib/global/libs/matrix/rooms.dart
- lib/global/print.dart
- lib/global/values.dart
- lib/storage/middleware/save-storage-middleware.dart
- lib/store/auth/actions.dart
- lib/store/crypto/actions.dart
- lib/store/crypto/events/actions.dart
- lib/store/crypto/keys/actions.dart
- lib/store/crypto/sessions/actions.dart
- lib/store/crypto/sessions/converters.dart
- lib/store/crypto/sessions/service/actions.dart
- lib/store/crypto/sessions/service/functions.dart
- lib/store/events/messages/storage.dart
- lib/store/events/model.dart
- lib/store/rooms/actions.dart
- lib/store/rooms/room/model.dart
- lib/store/sync/actions.dart
- lib/store/sync/parsers/parsers.dart
- lib/store/sync/service/service.dart
- makefile
- pubspec.yaml
> [fix] Release 0.2.14 Reset and Fixes

- lib/views/home/settings/settings-privacy-screen.dart
add Haptic Feedback to everything copyable on Settings/Privacy screen
> [feature] add Haptic Feedback to everything copyable on Settings/Privacy screen

- lib/views/widgets/modals/modal-user-details.dart
Added function which copies a username to the clipboard see #690
> [feature] Copy user by holding

- lib/store/settings/actions.dart
https://spec.matrix.org/v1.4/client-server-api/#private-read-receipts
> fix: Private Read Receipts have hit a spec version!

- version.txt
> Bump F-Droid 0.2.14
